[package]
name = "rustLy-tui"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustLy-conf.workspace = true

# none rustLy
termbox = "0.2.0"
